name: Build NanoBolt

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies - common
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install dependencies - test
        run: |
          if [ -f requirements.test.txt ]; then pip install -r requirements.test.txt; fi

      - name: Install dependencies - release
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.release.txt ]; then pip install -r requirements.release.txt; fi

      - name: Build package
        run: |
          # Command to build your package goes here.
