---

name: Build NanoBolt

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies - common
        run: |
          make setup-dev

      - name: Install dependencies - test
        run: |
          make setup-test

      - name: Install dependencies - release
        run: |
          make setup-release

      - name: Build package
        run: |
          # Command to build your package goes here.
