---
name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-commit:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check-commit.outputs.skip }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: check if message contain keywords ace scopeid
        id: check-commit
        run: |
          # checking for "docs" or "[ci skip]" messages
          message=$(git log -1 --pretty=format:'%s')
          if [[ "$message" =~ "(\[doc\])|(\[minor\])|(\[skip\])" ]]; then
            echo "Skipping tests due to [doc], [minor], or [skip] message"
            echo "::set-output name=skip::true"
          fi

  validate:
    timeout-minutes: 45
    defaults:
      run:
        shell: bash
    needs: check-commit
    if: ${{ steps.check-commit.outputs.skip != 'true' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
    outputs:
      matrix: ${{ steps.read-metadata.outputs.matrix }}
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}

    steps:
      - name: Read Metadata and Generate Matrix
        id: read-metadata
        run: |
          json=$(python .github/commands/matrix metadata.json)
          echo "::set-output name=matrix::$json"

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          make setup

      - name: Check - if tests exist
        id: has_tests
        uses: andstor/file-existence-action@v2
        with:
          files: "tests"

      - name: Run - tests
        if: steps.has_tests.outputs.files_exists == 'true'
        run: |
          make tests

      - name: Build - package
        run: |
          make package

  publish-test-results:
    name: publish-test-results
    needs: validate
    if: ${{ steps.check-commit.outputs.skip != 'true' && steps.has_tests.outputs.files_exists == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: download test-results
        uses: actions/download-artifact@v3
        with:
          path: test-results

      - name: Publish - test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          check_name: Test Results
          github_token: ${{ secrets.GITHUB_TOKEN }}
          junit_files: test-results/**/*.xml
          comment_mode: "off"
