---
name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-commit:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check-commit.outputs.skip }}
      matrix: ${{ steps.check-commit.outputs.matrix }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: check if message contain escape keywords
        id: check-commit
        run: |
          # checking for "[docs]" or "[skip]" messages
          message=$(git log -1 --pretty=format:'%s')
          if [[ "$message" =~ "(\[doc\])|(\[minor\])|(\[skip\])" ]]; then
            echo "Skipping tests due to [doc], [minor], or [skip] message"
            echo "::set-output name=skip::true"
          fi

      - name: Read Metadata
        id: read-metadata
        run: |
          matrix=$(make matrix)
          echo "::set-output name=matrix::$matrix"

  validate:
    timeout-minutes: 45
    defaults:
      run:
        shell: bash
    needs: check-commit
    if: ${{ needs.check-commit.outputs.skip != 'true' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      mat: ${{ fromJson(needs.read-metadata.outputs.matrix) }}
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.9", "3.10"]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install - dependencies
        run: |
          make setup

      - name: Check - if tests exist
        id: has_tests
        uses: andstor/file-existence-action@v2
        with:
          files: "tests"

      - name: Test - execute ${{ matrix.index }}
        if: steps.has_tests.outputs.files_exists == 'true'
        run: |
          make tests

      - name: Test - upload results ${{ matrix.index }}
        if: steps.has_tests.outputs.files_exists == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.index }}
          path: output/report/test/junit.xml

      - name: Build - package
        run: |
          make package

  publish-test-results:
    name: publish-test-results
    needs: validate
    # the build-and-test job might be skipped, we don't need to run this job then
    if: success() || failure()
    runs-on: ubuntu-latest
    permissions:
      checks: write
      # only needed unless run with comment_mode: off
      pull-requests: write
      # only needed for private repository
      contents: read
      # only needed for private repository
      issues: read

    steps:
      - name: Test - download results
        uses: actions/download-artifact@v3
        with:
          path: test-results

      - name: Publish - test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          check_name: Test Results
          github_token: ${{ secrets.GITHUB_TOKEN }}
          junit_files: test-results/**/*.xml
          comment_mode: "always"
